spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    # ImMemory
    url: jdbc:h2:mem:locator
    #    tcp: jdbc:h2:tcp://localhost:9092/mem:locator
    # Relative path form current dir
    #    url: jdbc:h2:./db/locator
    # Relative path from home
    #    url: jdbc:h2:~/locator
    #    tcp: jdbc:h2:tcp://localhost:9092/~/locator
    username: admin
    password: 12345
  h2.console.enabled: true

  profiles:
    active: multi-thread
#    active: single-thread

rating-cache:
  lifetime: 60_000
  sleep: 10_000
  rating: 5
  batchsize: 20
  usegc: true
  savememory: true


logging:
  level:
    root: WARN
    com.atanava.locator: DEBUG
#    org.springframework.security.web.FilterChainProxy: DEBUG
